title = "Warren Nelson"
baseurl = "https://warrennelson.me/"
languageCode = "en-us"
theme = "warrennelson-theme"
googleAnalytics = "UA-61430114-1"
disqusShortname = "warren-nelson"


[permalinks]
	blog = "/blog/:year/:month/:slug"